# **Udacity: Intro to TensorFlow for Deep Learning**
### **Lesson 9 NLP: Tokenization and Embeddings**

**Introduction to NLP**   
This lesson was an introduction to natural language processing, which involves analysing the meaning of text and speech data. Applications of NLP include
- Dictation and translation
- Sentiment analysis
- Text and speech generation

We have also seen NLP been applied in commerical products like voice assistants and other smart devices.

</br>

This lesson focuses on how we can prepare text data for our NLP models

## **Preparing Text for Natural language models**

Towards preparing text for NLP models we would need to
- **Tokenize the text**, which involves assigning a numerical value to words in the text training dataset
- We typically work with sentences and not just individual words in NLP, so after tokenization, we can then **convert sentences into sequences**.
- As we can have sentences of different lengths, we would also have sequences of different length, to work around this we would apply **padding and truncating** to ensure all the sequences have equal length.

<br/>

Other things and parameters to account for   
- Tokenization is only applied once and with the training set, any new words encountered in the test set would be represented with an **Out of vocabulary token, OOV**.
- We can define the **number of words which would get tokenized**.
- We can vary the **length of our sequences**, using padding and truncating.
- we can define **where padding and truncating is applied**, at the start or end of sequences.

## **Import required packages**

In [ ]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

print(tf.__version__)

2.8.2


## **Tokenization**

Lets use text from Green Eggs and Ham by Dr. Seuss.



In [ ]:
# define a list of sentences
Green_eggs_and_ham = ["I AM SAM. I AM SAM. SAM I AM.",
                      "THAT SAM-I-AM! THAT SAM-I-AM! I DO NOT LIKE THAT SAM-I-AM!",
                      "DO WOULD YOU LIKE GREEN EGGS AND HAM?",
                      "I DO NOT LIKE THEM,SAM-I-AM.",
                      "I DO NOT LIKE GREEN EGGS AND HAM.",
                      "WOULD YOU LIKE THEM HERE OR THERE?",
                      "I WOULD NOT LIKE THEM HERE OR THERE.",
                      "I WOULD NOT LIKE THEM ANYWHERE.",
                      "I DO NOT LIKE GREEN EGGS AND HAM.",
                      "I DO NOT LIKE THEM, SAM-I-AM.",

                      "WOULD YOU LIKE THEM IN A HOUSE?",
                      "WOULD YOU LIKE THEN WITH A MOUSE?",

                      "I DO NOT LIKE THEM IN A HOUSE.",
                      "I DO NOT LIKE THEM WITH A MOUSE.",
                      "I DO NOT LIKE THEM HERE OR THERE.",
                      "I DO NOT LIKE THEM ANYWHERE.",
                      "I DO NOT LIKE GREEN EGGS AND HAM.",
                      "I DO NOT LIKE THEM, SAM-I-AM.",

                      "WOULD YOU EAT THEM IN A BOX?",
                      "WOULD YOU EAT THEM WITH A FOX?",

                      "NOT IN A BOX. NOT WITH A FOX.",
                      "NOT IN A HOUSE. NOT WITH A MOUSE.",
                      "I WOULD NOT EAT THEM HERE OR THERE.",
                      "I WOULD NOT EAT THEM ANYWHERE.",
                      "I WOULD NOT EAT GREEN EGGS AND HAM.",
                      "I DO NOT LIKE THEM, SAM-I-AM.",

                      "WOULD YOU? COULD YOU? IN A CAR?",
                      "EAT THEM! EAT THEM! HERE THEY ARE.",

                      "I WOULD NOT, COULD NOT, IN A CAR.",

                      "YOU MAY LIKE THEM. YOU WILL SEE.",
                      "YOU MAY LIKE THEM IN A TREE!",

                      "I WOULD NOT, COULD NOT IN A TREE.",
                      "NOT IN A CAR! YOU LET ME BE.",
                      "I DO NOT LIKE THEM IN A BOX.",
                      "I DO NOT LIKE THEM WITH A FOX.",
                      "I DO NOT LIKE THEM IN A HOUSE.",
                      "I DO NOT LIKE THEM WITH A MOUSE.",
                      "I DO NOT LIKE THEM HERE OR THERE.",
                      "I DO NOT LIKE THEM ANYWHERE.",
                      "I DO NOT LIKE GREEN EGGS AND HAM.",
                      "I DO NOT LIKE THEM, SAM-I-AM.",

                      "A TRAIN! A TRAIN! A TRAIN! A TRAIN!",
                      "COULD YOU, WOULD YOU ON A TRAIN?",

                      "NOT ON TRAIN! NOT IN A TREE!",
                      "NOT IN A CAR! SAM! LET ME BE!",
                      "I WOULD NOT, COULD NOT, IN A BOX.",
                      "I WOULD NOT, COULD NOT, WITH A FOX.",
                      "I WILL NOT EAT THEM IN A HOUSE.",
                      "I WILL NOT EAT THEM HERE OR THERE.",
                      "I WILL NOT EAT THEM ANYWHERE.",
                      "I DO NOT EAT GREEM EGGS AND HAM.",
                      "I DO NOT LIKE THEM, SAM-I-AM.",
]

**Defining and fitting the tokenizer and word index**

In [ ]:
# initialize the tokenizer, it would tokenize the 100 most common words in the list of sentences
green_eggs_and_ham_tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")

# fit the tokenizer to the list of sentences
green_eggs_and_ham_tokenizer.fit_on_texts(Green_eggs_and_ham)


View the word index for the tokenizer

In [ ]:
word_index = green_eggs_and_ham_tokenizer.word_index
print(word_index)
print("Number of tokenized words: {}".format(len(word_index)))

{'<OOV>': 1, 'i': 2, 'not': 3, 'them': 4, 'like': 5, 'a': 6, 'do': 7, 'would': 8, 'in': 9, 'you': 10, 'sam': 11, 'am': 12, 'eat': 13, 'with': 14, 'eggs': 15, 'and': 16, 'ham': 17, 'here': 18, 'green': 19, 'or': 20, 'there': 21, 'could': 22, 'train': 23, 'anywhere': 24, 'house': 25, 'mouse': 26, 'box': 27, 'fox': 28, 'car': 29, 'will': 30, 'that': 31, 'tree': 32, 'may': 33, 'let': 34, 'me': 35, 'be': 36, 'on': 37, 'then': 38, 'they': 39, 'are': 40, 'see': 41, 'greem': 42}
Number of tokenized words: 42


An intresting note,
- it hasn't picked on any of the exclamation marks, commas or periods in the sentences.
- it also has 42 words in its word index and not 100, so i'm guess that it only found 42 words which were very common in the entire list and it could not find 58 other words which were also very common


</br>

some questions to raise
- How often does the word have to come up in the sentence for it to be added to the word index, or does it just find the frequency of each word and then sort and filter based on frequency and desired number of words.


**Convert text to sequences**

In [ ]:
# get a single sentence from the list of sentences
sample_sentence = Green_eggs_and_ham[0]
print(sample_sentence)


I AM SAM. I AM SAM. SAM I AM.


In [ ]:
# convert the sentence into a sequence
green_eggs_and_ham_tokenizer.texts_to_sequences([sample_sentence])

[[2, 12, 11, 2, 12, 11, 11, 2, 12]]

In [ ]:
# get more sentences from the list and convert it into sequences

sample_sentences = Green_eggs_and_ham[0:10]
sample_sequences = green_eggs_and_ham_tokenizer.texts_to_sequences(sample_sentences)

for text, sequence in zip(sample_sentences, sample_sequences):
  print("Text: {}".format(text))
  print("Sequence: {}".format(sequence))
  print("\n")


Text: I AM SAM. I AM SAM. SAM I AM.
Sequence: [2, 12, 11, 2, 12, 11, 11, 2, 12]


Text: THAT SAM-I-AM! THAT SAM-I-AM! I DO NOT LIKE THAT SAM-I-AM!
Sequence: [31, 11, 2, 12, 31, 11, 2, 12, 2, 7, 3, 5, 31, 11, 2, 12]


Text: DO WOULD YOU LIKE GREEN EGGS AND HAM?
Sequence: [7, 8, 10, 5, 19, 15, 16, 17]


Text: I DO NOT LIKE THEM,SAM-I-AM.
Sequence: [2, 7, 3, 5, 4, 11, 2, 12]


Text: I DO NOT LIKE GREEN EGGS AND HAM.
Sequence: [2, 7, 3, 5, 19, 15, 16, 17]


Text: WOULD YOU LIKE THEM HERE OR THERE?
Sequence: [8, 10, 5, 4, 18, 20, 21]


Text: I WOULD NOT LIKE THEM HERE OR THERE.
Sequence: [2, 8, 3, 5, 4, 18, 20, 21]


Text: I WOULD NOT LIKE THEM ANYWHERE.
Sequence: [2, 8, 3, 5, 4, 24]


Text: I DO NOT LIKE GREEN EGGS AND HAM.
Sequence: [2, 7, 3, 5, 19, 15, 16, 17]


Text: I DO NOT LIKE THEM, SAM-I-AM.
Sequence: [2, 7, 3, 5, 4, 11, 2, 12]




Side note
- The texts_to_sequences function takes in a list of texts, so we can not just pass in raw stings

**Closer look at the Tokenizers Doc**

[Tokenizer Doc](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer)

<br/>

**tf.keras.preprocessing is deprecated**   
It looks like keras.preprocessing module is deprecated in version 2.9.1, it is now suggested to use the 
*tf.keras.utils.text_dataset_from_directory* and *tf.keras.layers.TextVectorization* for preprocessing text input.

For the sake of continuity with the course, i will follow along with using the depreciated code, but i'd still checkout the new methods for preprocessing text in another notebook.

<br/>

**Other methods with the Text tokenizer**
- fit_on_sequence / texts
- sequence to matrix / texts and text generators
- text to matrix / sequnce and sequence generators
- get_config
- to_json

<br/>

With going into too much detail on each function it seems like not only can we convert text into sequences, we can also convert them into matrix and we can only fit to sequences.


## **Padding and Truncating**

Side note again
- Looking at the documentation for version 2.9.1, pad_sequences has been moved to *tf.keras.utils.pad_sequences*

<br/>

Default behaviours
- Padding and truncating is applied at the start of the sequences
- max_length of sequence is decided by the longest sequence in the list, unless specified in the class constructor.
- padding value is 0

<br/>

i'd still try to see if i can use pad_sequence which i thought was imported from *tf.keras.preprocessing.sequence*.





In [ ]:
# lets take sample_sequences
for sequence in sample_sequences:
    print(sequence)

[2, 12, 11, 2, 12, 11, 11, 2, 12]
[31, 11, 2, 12, 31, 11, 2, 12, 2, 7, 3, 5, 31, 11, 2, 12]
[7, 8, 10, 5, 19, 15, 16, 17]
[2, 7, 3, 5, 4, 11, 2, 12]
[2, 7, 3, 5, 19, 15, 16, 17]
[8, 10, 5, 4, 18, 20, 21]
[2, 8, 3, 5, 4, 18, 20, 21]
[2, 8, 3, 5, 4, 24]
[2, 7, 3, 5, 19, 15, 16, 17]
[2, 7, 3, 5, 4, 11, 2, 12]


In [ ]:
# apply padding to the sequence to make it have a length of 10
padded_sample_sequences = pad_sequences(sample_sequences, maxlen=10,
                                        padding='pre', truncating='post')

for sequence in padded_sample_sequences:
  print(sequence)

[ 0  2 12 11  2 12 11 11  2 12]
[31 11  2 12 31 11  2 12  2  7]
[ 0  0  7  8 10  5 19 15 16 17]
[ 0  0  2  7  3  5  4 11  2 12]
[ 0  0  2  7  3  5 19 15 16 17]
[ 0  0  0  8 10  5  4 18 20 21]
[ 0  0  2  8  3  5  4 18 20 21]
[ 0  0  0  0  2  8  3  5  4 24]
[ 0  0  2  7  3  5 19 15 16 17]
[ 0  0  2  7  3  5  4 11  2 12]


That seems straightforward, i've applied pre padding, so that padding is applied at the start of the sequence and i used post truncating to truncate from the end of the sequence.

## **Word Embeddings**

Word embeddings, represent individual words in our tokenized vocabulary as vectors in an n dimensional space.

<br/>

What does this mean?   
- a word would be represented as a vector of n dimensions
- Example if we have 5 dimensions, a word like "Ham" would be represented as [0, 4, 2, 9, 10]


<br/>

My issue with this is that, why i would not pretend to fully understand Embeddings, does it not make the whole process of tokenization and sampling obsolete?, if we would simply end up with words converted into vectors of n dimension, Why go through the steps of 2 previous steps??




Link to the [Embeddings Doc](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding)

In [ ]:
# import the Embeddings layer
from tensorflow.keras.layers import Embedding



In [ ]:
# define an Embeddings layer, which returns a vector represented in 10 dimensions.

green_eggs_and_ham_embedding_layer = Embedding(input_dim = 100, output_dim = 10, input_length=10)

lets try out the embedding layer on some of the sequence and view the output

In [ ]:
one_padded_sequence = padded_sample_sequences[0]
print(one_padded_sequence)

output = green_eggs_and_ham_embedding_layer(one_padded_sequence)
print(output)

[ 0  2 12 11  2 12 11 11  2 12]
tf.Tensor(
[[-0.03021989  0.01281465 -0.04905542 -0.04851932 -0.02706047  0.04161533
   0.00115458 -0.04174959 -0.010993   -0.04647777]
 [ 0.03158594  0.02095946  0.03878237  0.04323217 -0.0496304  -0.0044466
  -0.01157327  0.01833392  0.00045573  0.00308537]
 [-0.03898587  0.03261942  0.00892892  0.03284807 -0.03724285  0.02448977
  -0.03382075 -0.01881353  0.03247478  0.01001913]
 [-0.01517288  0.03596203 -0.00664157  0.00320182  0.00103928 -0.03119476
   0.02087155  0.00902732 -0.01722797  0.02964315]
 [ 0.03158594  0.02095946  0.03878237  0.04323217 -0.0496304  -0.0044466
  -0.01157327  0.01833392  0.00045573  0.00308537]
 [-0.03898587  0.03261942  0.00892892  0.03284807 -0.03724285  0.02448977
  -0.03382075 -0.01881353  0.03247478  0.01001913]
 [-0.01517288  0.03596203 -0.00664157  0.00320182  0.00103928 -0.03119476
   0.02087155  0.00902732 -0.01722797  0.02964315]
 [-0.01517288  0.03596203 -0.00664157  0.00320182  0.00103928 -0.03119476
   0.02087

It looks like it has done exactly what we want it to do. For each word (token) in the sequence, it has created a vector represented in 10 dimensions.

Are the vector representation of each token consistent??   
- yes they are, check token 2, 12 & 11. it's consistent

**Using the embeddings layer with flatten and globalAverage pooling**

In [ ]:
from tensorflow.keras.layers import Flatten, GlobalAveragePooling1D


In [ ]:
def embeddings_with_flatten(sequence):
  """ Output result of calling embedding with flatten layer."""
  embedding_output = Embedding(input_dim=100, output_dim=10, input_length=10)(sequence)
  return Flatten()(embedding_output)


In [ ]:
# calling embeddings with flatten
output_1 = embeddings_with_flatten(one_padded_sequence)
print(output_1)


tf.Tensor(
[[ 0.01029031  0.04661094  0.023269    0.00515274  0.04184343  0.00934483
   0.04358728 -0.04875825  0.01074376 -0.039929  ]
 [-0.00071131 -0.0477136   0.02663224  0.02124919 -0.03404929 -0.0209569
  -0.00733783 -0.01769852 -0.02028185 -0.0470591 ]
 [-0.03174638 -0.04209901 -0.02665803  0.00995724 -0.02815077 -0.02901781
   0.04438217  0.03840314 -0.04537207  0.04851108]
 [-0.03818735  0.00078509  0.04093063  0.0094205   0.01967049  0.03563208
   0.03785429 -0.03872411 -0.0254331  -0.03612403]
 [-0.00071131 -0.0477136   0.02663224  0.02124919 -0.03404929 -0.0209569
  -0.00733783 -0.01769852 -0.02028185 -0.0470591 ]
 [-0.03174638 -0.04209901 -0.02665803  0.00995724 -0.02815077 -0.02901781
   0.04438217  0.03840314 -0.04537207  0.04851108]
 [-0.03818735  0.00078509  0.04093063  0.0094205   0.01967049  0.03563208
   0.03785429 -0.03872411 -0.0254331  -0.03612403]
 [-0.03818735  0.00078509  0.04093063  0.0094205   0.01967049  0.03563208
   0.03785429 -0.03872411 -0.0254331  -0.0

In [ ]:
# define the function
def embeddings_with_globalaveragepool(sequence):
  embedding_output = Embedding(input_dim=100, output_dim=10, input_length=10)(sequence)
  print(embedding_output)
  reshaped_embedding = tf.keras.layers.Reshape((10, 1))(embedding_output)
  print(reshaped_embedding)
  return GlobalAveragePooling1D()(reshaped_embedding)

# callings with embeddings with global average pooling
output_2 = embeddings_with_globalaveragepool(one_padded_sequence)
print(output_2)

tf.Tensor(
[[ 0.02531358  0.02799585 -0.01580938  0.01671995 -0.02855491  0.03134619
  -0.02139058 -0.01615366 -0.02857158 -0.01546197]
 [ 0.04141453 -0.03586144  0.04468853  0.00243197  0.0425258   0.02570314
   0.03169549 -0.00939401 -0.00173203  0.02032695]
 [ 0.00069119  0.0211736  -0.04973649  0.00702355 -0.03485416 -0.00299828
   0.02871437 -0.04768872  0.00744121 -0.02722271]
 [-0.01300015  0.03453108  0.04390124 -0.02796248 -0.01919132  0.0014916
   0.03302205  0.0110528   0.02355763  0.03311569]
 [ 0.04141453 -0.03586144  0.04468853  0.00243197  0.0425258   0.02570314
   0.03169549 -0.00939401 -0.00173203  0.02032695]
 [ 0.00069119  0.0211736  -0.04973649  0.00702355 -0.03485416 -0.00299828
   0.02871437 -0.04768872  0.00744121 -0.02722271]
 [-0.01300015  0.03453108  0.04390124 -0.02796248 -0.01919132  0.0014916
   0.03302205  0.0110528   0.02355763  0.03311569]
 [-0.01300015  0.03453108  0.04390124 -0.02796248 -0.01919132  0.0014916
   0.03302205  0.0110528   0.02355763  0.03

## **Subwords**